import { NextResponse } from "next/server";

//export async function GET(request) {
//  const { searchParams } = new URL(request.url);
//  const persona = searchParams.get("persona") || "STRICT_PROFESSOR";

//  const sessionConfig = {
//    model: "models/gemini-3.1-flash-live-preview",
//    generationConfig: {
//      responseModalities: ["AUDIO"],
//      speechConfig: {
//        voiceConfig: {
//          prebuiltVoiceConfig: {
//            voiceName: "Puck", //Puck, Charon, Kore, Fenrir, Aoede
//          },
//        },
//      },
//    },
//    systemInstruction: {
//      parts: [
//        {
//          text: `You are Speak2Prep, an autonomous AI technical examiner conducting a live oral viva for an Application Security (AppSec) Engineer role. 
//Persona Mode: ${persona}.
//Ask precise, scenario-based technical questions one at a time. Keep spoken answers concise (2 to 3 sentences max) so it feels like a real phone call. If the candidate's answer is weak, probe deeper into mitigations or edge cases.`,
//        },
//      ],
//    },
//  };

//  return NextResponse.json({ config: sessionConfig });
//}


export async function POST(request) {
  try {
    const { persona, blueprint } = await request.json();

    //Default instruction fallback if no syllabus blueprint is provided
    let instructionText = `You are Speak2Prep, an autonomous AI technical examiner conducting a live oral viva for an Application Security (AppSec) Engineer role.
Persona Mode: ${persona || "STRICT_PROFESSOR"}.
Ask precise, scenario-based technical questions one at a time. Keep spoken answers concise (2 to 3 sentences max) so it feels like a real phone call. If the candidate's answer is weak, probe deeper into mitigations or edge cases.`;

    //Overwrite with dynamic syllabus blueprint instruction if generated by Agent 1
    if (blueprint?.formattedSystemInstruction) {
      instructionText = blueprint.formattedSystemInstruction;
    } else if (blueprint?.coreModules) {
      const topicsList = blueprint.coreModules
        .map((m) => `${m.moduleName}: ${m.keyConcepts.join(", ")}`)
        .join("\n- ");

      instructionText = `You are Speak2Prep, an AI technical examiner conducting a live oral viva.
Target Role: ${blueprint.subjectTitle || "Technical Specialist"}.
Persona Mode: ${persona || "STRICT_PROFESSOR"}.

SYLLABUS CORE TOPICS TO COVER:
- ${topicsList}

CONDUCT RULES:
1. Ask one scenario-based question at a time focused on the syllabus topics above.
2. Keep spoken turns brief (2-3 sentences max).
3. Do not list multiple questions at once.
4. Probe deeply into candidate responses if they use buzzwords without explaining mechanisms.`;
    }

    const sessionConfig = {
      model: "models/gemini-3.1-flash-live-preview",
      generationConfig: {
        responseModalities: ["AUDIO"],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: "Puck",
            },
          },
        },
      },
      systemInstruction: {
        parts: [{ text: instructionText }],
      },
    };

    return NextResponse.json({ config: sessionConfig });
  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}